version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/SellerReturnApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=returns_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - returns-net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: returns_db
    ports:
      - "5432:5432"
    volumes:
      - pg/var/lib/postgresql/data
    networks:
      - returns-net

volumes:
  pgdata:

networks:
  returns-net:
    driver: bridge